---
apiVersion: v1
kind: Namespace
metadata:
  name: zeek
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeek
  namespace: zeek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeek
  template:
    metadata:
      labels:
        app: zeek
    spec:
      containers:
      - name: nginx
        image: nginx:1.29.1
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      - name: sensor
        image: zeek-with-extras:0.0.1
        workingDir: /usr/local/zeek/logs
        command:
          - /usr/local/zeek/bin/zeek
        args:
          - -i
          - eth0
          - -C
          - LogAscii::use_json=T
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        volumeMounts:
        - name: zeek-logs
          mountPath: /usr/local/zeek/logs
      - name: fluentbit
        image: grafana/fluent-bit-plugin-loki:3.1.2
        imagePullPolicy: IfNotPresent         
        ports:
          - name: metrics
            containerPort: 2020
            protocol: TCP
        volumeMounts:
          - name: config-volume
            mountPath: /fluent-bit/etc/
          - name: zeek-logs
            mountPath: /usr/local/zeek/logs
      volumes:
        - name: zeek-logs
          emptyDir: {}
        - name: config-volume
          configMap:
            name: fluent-bit
---
apiVersion: v1
kind: Service
metadata:
  name: zeek
spec:
  selector:
    app: zeek
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zeek
  namespace: zeek
spec:
  ingressClassName: "traefik"
  rules:
  - host: zeek.k3d.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zeek
            port:
              number: 80