apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: grafana
  namespace: kube-system
spec:
  repo: https://grafana.github.io/helm-charts
  chart: grafana
  targetNamespace: grafana
  createNamespace: true
  valuesContent: |-
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: loki
          type: loki
          url: http://grafana-loki-gateway.loki.svc.cluster.local
          jsonData:
            httpHeaderName1: 'X-Scope-OrgId'
          secureJsonData:
            httpHeaderValue1: 'zeek'
